#!/usr/local/scholarly-python2/bin/python

import sys
sys.path.append('../')
import argparse
import logging
import ConfigParser
import os.path
from lxml import html, etree
from indexer.Indexer import Indexer
from indexer.Crawler import Crawler






if __name__ == "__main__":

    # read and check the options
    parser = argparse.ArgumentParser(description='eSRC Transform Test tool')

    parser.add_argument('--config',   dest='config', required=True, help='The path to the default Indexer configuration.')
    parser.add_argument('--site',     dest='site',   required=True, help='The site to process.')

    parser.add_argument('--doc', dest='document', required=True,
        help="Transform a single document and write the result to STDOUT. ONLY USE THE HTML DOCUMENT.\
        If there's an XML representation the code will find it.")

    args = parser.parse_args()

    # get the logger
    logging.basicConfig(level=logging.DEBUG)
    log = logging.getLogger('TRANSFORM')

    # check the arguments
    if not os.path.exists(args.config):
        log.error("Does %s exist?" % args.config)
        sys.exit()

    log.debug("Indexing: %s" % args.site)

    i = Indexer(args.site, args.config)
    print i.ohrm_cfg
    c = Crawler(i.ohrm_cfg)
    tree = html.parse(args.document)
    document = c.which_file(tree, args.document)
    i.transform([], document=document[0], doctype=document[1])




